### ISSUE TITLE
Fails for multiple domains

### ISSUE THREAD

**Issue by karlmdavis** [L-P/ansible-role-acmetool#1]
I've got the following configuration for this role, which doesn't work:

```
acmetool_domains: "{{ [domain] | union(domain_site_aliases) | join(' ') }}"
```

This just expands to `tests.justdavis.com www.tests.justdavis.com tests.davisonlinehome.name www.tests.davisonlinehome.name", as you can see in the following Ansible `-vvv` output, along with the error that the space-separated domins cause:

```
changed: [eddings.justdavis.com] => {"changed": true, "cmd": ["acmetool", "want", "--batch", "tests.justdavis.com www.tests.justdavis.com tests.davisonlinehome.name www.t
ests.davisonlinehome.name"], "delta": "0:00:00.029405", "end": "2016-11-28 20:46:27.699574", "invocation": {"module_args": {"_raw_params": "acmetool want --batch \"tests.
justdavis.com www.tests.justdavis.com tests.davisonlinehome.name www.tests.davisonlinehome.name\"", "_uses_shell": false, "chdir": null, "creates": null, "executable": nu
ll, "removes": null, "warn": true}, "module_name": "command"}, "rc": 0, "start": "2016-11-28 20:46:27.670169", "stderr": "20161128204627 [ERROR] acme.storage: failed to l
oad target tests.justdavis.com www.tests.justdavis.com tests.davisonlinehome.name www.tests.davisonlinehome.name-4dh5nisfojfjjjdnyh47piv7wi: invalid target: tests.justdav
is.com www.tests.justdavis.com tests.davisonlinehome.name www.tests.davisonlinehome.name-4dh5nisfojfjjjdnyh47piv7wi: invalid hostname: \"tests.justdavis.com www.tests.jus
tdavis.com tests.davisonlinehome.name www.tests.davisonlinehome.name\"\n20161128204627 [ERROR] acme.storage: failed to load target tests.justdavis.com www.tests.justdavis
.com tests.davisonlinehome.name www.tests.davisonlinehome.name-4dh5nisfojfjjjdnyh47piv7wi: invalid target: tests.justdavis.com www.tests.justdavis.com tests.davisonlineho
me.name www.tests.davisonlinehome.name-4dh5nisfojfjjjdnyh47piv7wi: invalid hostname: \"tests.justdavis.com www.tests.justdavis.com tests.davisonlinehome.name www.tests.da
visonlinehome.name\"", "stdout": "", "stdout_lines": [], "warnings": []}
```

It's passing the space-separated domains as a single argument, which effectively escapes the spaces. I think this can be resolved by either quoting the command in `ansible-role-acmetool/tasks/main.yml`, or perhaps by switching to the `shell` module? Something like that, anyways.

**Comment by L-P** [comment]
Hi,

Does your commit [9bf28d](https://github.com/karlmdavis/ansible-role-acmetool/commit/9bf281d8905a51c4809abb66c4466485476f4416) fix anything? What version of Ansible are you using?

Multiple domains works with a "static" declaration (ie. no `{{…}}`)
using Ansible  2.2.0.0, what happens if you specify your domains this
way?

If you put quotes around [tasks/main.yml:9](https://github.com/L-P/ansible-role-acmetool/blob/master/tasks/main.yml#L9) does it change anything?

I don't fully understand how Ansible handles string interpolation,
escaping in `command`, and how YAML interferes with all that. I can only
guess.
