### ISSUE TITLE
Using the generated systemd configuration

### ISSUE THREAD

**Issue by Mayeu** [L-P/ansible-role-acmetool#2]
Hello,

First I would like to thank you for the playbook, I have been using it for a while now!

There is an issue with the redirector feature, in the fact that your service file is running as the `acme` user who does not have the right to bind the port 80.

While I was fixing it, I stumble across the fact that acmetool [can generate its own service file](https://github.com/hlandau/acme/blob/83d2466ceb01a76d281ff8983465db191fbfa1e2/cmd/acmetool/quickstart-linux.go#L70).

I believe it would be less maintenance to use the provided generated service file instead of using a new one. What do you think?

**Comment by L-P** [comment]
Hi,

Sorry for the delay, I did not receive a notification for this issue.

Not using the acme-generated .service file is a feature, the idea is to run
acmetool as its own user and not let a root process handle incoming traffic.

In the generated .service, the process starts as root and then drops
privileges. I don't want it to ever run as root because it does not need to: 
in [setup.yml][1] we add capabilities to the executable so it can bind to :80
as an unprivileged user.

Can you tell me more about the original binding issue? Because it works for
me™.

[1]: https://github.com/L-P/ansible-role-acmetool/blob/7a2ce609eed44451c8073e2bbb19122bb7c45b34/tasks/setup.yml#L10

**Comment by Mayeu** [comment]
Hello,

Sorry for the long delay, I don't use acmetool tool anymore I switched everything to certbot instead so I can't really try that at all anymore!

So I close the ticket since the issue does not really exist anymore :)

Cheers,
